# Site settings
title: Reda Mazoz Portfolio Website
description: A blog about Reda Mazoz Projects and Resume
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "https://tensadev.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: TensaDev
user_description: tensadev
user_title: Gameplay Developer
email: redamazoz21@gmail.com
twitter_username: lorem_ipsum
github_username:  Tensadev
fb_username:  Reda Mazoz

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
